from datetime import date
from pathlib import Path

import pandas as pd


REQUESTS_FILE = Path(__file__).resolve().parent.parent / "data" / "hr_requests.csv"

REQUEST_COLUMNS = [
    "request_id",
    "employee_id",
    "request_type",
    "request_text",
    "request_date",
    "leave_start_date",
    "leave_end_date",
    "working_days_requested",
    "status",
    "manager_username",
    "approval_required",
    "approval_level",
    "policy_check_result",
    "rejection_reason",
    "source_channel",
]


def load_requests():
    """
    Load requests table from CSV.
    Missing files/columns are created to keep MVP robust.
    """
    if not REQUESTS_FILE.exists():
        empty_df = pd.DataFrame(columns=REQUEST_COLUMNS)
        empty_df.to_csv(REQUESTS_FILE, index=False)
        return empty_df

    df = pd.read_csv(REQUESTS_FILE).fillna("")
    for column in REQUEST_COLUMNS:
        if column not in df.columns:
            df[column] = ""

    return df[REQUEST_COLUMNS]


def save_requests(df):
    """Persist request DataFrame to CSV."""
    df.to_csv(REQUESTS_FILE, index=False)


def _next_request_id(df):
    """Generate enterprise-like request id: HRR-YYYY-XXX."""
    year_str = str(date.today().year)
    if df.empty:
        return f"HRR-{year_str}-001"

    # Extract sequence for current year from existing ids.
    prefix = f"HRR-{year_str}-"
    seq_values = []
    for req_id in df["request_id"].astype(str):
        if req_id.startswith(prefix):
            parts = req_id.split("-")
            if len(parts) == 3 and parts[2].isdigit():
                seq_values.append(int(parts[2]))

    next_seq = max(seq_values) + 1 if seq_values else 1
    return f"HRR-{year_str}-{next_seq:03d}"


def create_request(employee_profile, request_type, request_text, leave_date="", leave_year=""):
    """
    Create a new request row.
    `leave_date` is used as both start/end date for one-day birthday leave.
    """
    df = load_requests()
    request_id = _next_request_id(df)
    request_date = date.today().isoformat()

    new_row = {
        "request_id": request_id,
        "employee_id": employee_profile["employee_id"],
        "request_type": request_type,
        "request_text": request_text,
        "request_date": request_date,
        "leave_start_date": leave_date or request_date,
        "leave_end_date": leave_date or request_date,
        "working_days_requested": 1,
        "status": "Pending",
        "manager_username": employee_profile.get("manager_username", ""),
        "approval_required": "TRUE",
        "approval_level": "Manager",
        "policy_check_result": "PASS: auto-generated by MVP assistant.",
        "rejection_reason": "",
        "source_channel": "portal",
    }

    updated_df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    save_requests(updated_df)
    return new_row


def get_employee_requests(employee_id):
    """Return requests created by one employee."""
    df = load_requests()
    result = df[df["employee_id"].astype(str) == str(employee_id)].copy()
    return result.sort_values("request_date", ascending=False)


def get_manager_pending_requests(manager_username):
    """Return pending requests assigned to one manager."""
    df = load_requests()
    pending_statuses = ["Pending", "Pending HR approval"]
    result = df[
        (df["manager_username"].astype(str) == str(manager_username))
        & (df["status"].isin(pending_statuses))
    ].copy()
    return result.sort_values("request_date", ascending=True)


def update_request_status(request_id, new_status):
    """Update request status by request_id."""
    df = load_requests()
    df.loc[df["request_id"].astype(str) == str(request_id), "status"] = new_status
    save_requests(df)


def has_active_birthday_request(employee_id, leave_year):
    """
    Check duplicate birthday leave for same year.
    If status is Rejected, it does not block a new request.
    """
    df = load_requests()
    birthday_rows = df[
        (df["employee_id"].astype(str) == str(employee_id))
        & (df["request_type"].astype(str).str.lower() == "birthday_leave")
        & (df["status"].astype(str) != "Rejected")
    ].copy()

    if birthday_rows.empty:
        return False

    # Use leave_start_date year as logical leave year.
    birthday_rows["leave_year"] = birthday_rows["leave_start_date"].astype(str).str[:4]
    matches = birthday_rows[birthday_rows["leave_year"] == str(leave_year)]
    return not matches.empty
